

int bookTotal=3;

char book[100][2][260]=
{
	{"《中国瓢虫亚科图志》",	"2010 虞国跃"},
	{"《台湾瓢虫图鉴》",	"2011 虞国跃,林义祥"},
	{"《中国瓢虫原色图鉴》",	"2009 任顺祥,王兴民,庞虹,彭正强,曾涛"},
};

int chswebsiteTotal=11;
char chswebsite[100][2][260]=
{
	{"国立自然科学博物馆",	"http://digimuse.nmns.edu.tw"},
	{"六足王国1",	"http://163.20.112.1/~afu/"},
	{"嘎嘎昆虫",	"http://gaga.biodiv.tw/"},
	{"四兽山昆虫调查网",	"http://sishou.artspacemedia.com"},
	{"自然摄影中心",	"http://nc.kl.edu.tw/bbs/index.php"},
	{"台湾物种名录",	"http://taibnet.sinica.edu.tw"},
	{"香港自然生态论坛",	"http://www.hkwildlife.net"},
	{"六足王国2",	"http://freebsd.tspes.ntpc.edu.tw/~afu/"},
	{"倾听自然论坛",	"http://nature.hc.edu.tw"},
	{"mbbrgs-520 Blog",	"http://tw.myblog.yahoo.com/mbbrgs-520/"},
	{"hsu042 Blog",	"http://www.wretch.cc/blog/hsu042"},
};

int intwebsiteTotal=65;

char intwebsite[100][2][260]=
{
	{"coccinellidae Peru",	"http://www.coccinellidae.cl/paginasWebPeru/Paginas/InicioPeru.php"},
	{"coccinellidae Cl",	"http://www.coccinellidae.cl"},
	{"coccinellidae Arg",	"http://www.coccinellidae.cl/paginasWebArg/Paginas/InicioArg.php"},
	{"coccinellidae Bra",	"http://www.coccinellidae.cl/paginasWebBra/Paginas/InicioBra.php"},
	{"coccinellidae Par",	"http://www.coccinellidae.cl/paginasWebPar/Paginas/InicioPar.php"},
	{"bugguide",	"http://bugguide.net/node/view/179"},
	{"discoverlife",	"http://www.discoverlife.org"},
	{"itis",	"http://www.itis.gov/"},
	{"insects jopan",	"http://www.insects.jp/konbunkouten.htm"},
	{"angelfire",	"http://www.angelfire.com/bug2/j_poorani/index.html"},
	{"people.duke.edu",	"http://people.duke.edu/~jspippen/naturephotos/coccinellidae.htm"},
	{"pbase",	"http://www.pbase.com/bo_z/ladybird_beetles__coccinellidae"},
	{"gvcocks",	"http://gvcocks.homeip.net"},
	{"InsectsofWestVirginia",	"http://www.insectsofwestvirginia.net/b/coccinellidae.html"},
	{"SaveOurWaterWaySnow",	"http://www.saveourwaterwaysnow.com.au"},
	{"uwm",	"http://www4.uwm.edu/fieldstation/naturalhistory/bugoftheweek/"},
	{"cirrusimage",	"http://www.cirrusimage.com/"},
	{"kendalluk",	"http://www.kendalluk.com/lbird.htm"},
	{"texasento",	"http://www.texasento.net"},
	{"kerbtier",	"http://www.kerbtier.de"},
	{"golddistel",	"http://www.golddistel.de/kaefer/coccinellidae/"},
	{"insect CZ",	"http://www.insect.cz/categories.php?cat_id=43"},
	{"tuin-thijs",	"http://www.tuin-thijs.com/kevers-ladybirds-ladybugs.htm"},
	{"meloidae",	"http://www.meloidae.com/en/category/coccinellidae-ladybird-beetles/"},
	{"eakringbirds",	"http://www.eakringbirds.com/eakringbirds4/photogallerythumbsbeetles.htm"},
	{"thewcg",	"http://www.thewcg.org.uk/pages/coccinellidae.htm"},
	{"BiodiversityExplorer",	"http://www.biodiversityexplorer.org/beetles/coccinellidae/"},
	{"chris-schuster",	"http://www.chris-schuster.com/Coccinellidae"},
	{"koleopterologie",	"http://www.koleopterologie.de/gallery/"},
	{"bumblebee",	"http://www.bumblebee.org/invertebrates/ColeopteraC.htm#ladybirds"},
	{"thaibugs",	"http://www.thaibugs.com"},
	{"BrisbaneInsects",	"http://www.brisbaneinsects.com/brisbane_ladybirds/index.html"},
	{"gardensafari",	"http://www.gardensafari.net/english/lady_bugs.htm"},
	{"toronto-wildlife",	"http://toronto-wildlife.com/Insects/Beetles/Ladybug/ladybugs.html"},
	{"pbase",	"http://www.pbase.com/terrythormin/coccinellidae"},
	{"animaldiversity",	"http://animaldiversity.ummz.umich.edu/accounts/Coccinellidae/pictures/"},
	{"LadybirdSurvey",	"http://www.ladybird-survey.org/species_list.aspx"},
	{"colinlmiller",	"http://colinlmiller.com/wildlife/coleoptera/beetles_coccinellidae.htm"},
	{"faunistik",	"http://www.faunistik.net/DETINVERT/COLEOPTERA/COCCINELLIDAE/coccinellidae.html"},
	{"skynet",	"http://users.skynet.be/verzamelen/lieveheersbeestjes-index.html"},
	{"david.element.ukgateway",	"http://www.david.element.ukgateway.net"},
	{"chinita-arlequin",	"http://www.chinita-arlequin.uchile.cl"},
	{"ccs-hk",	"http://www.ccs-hk.org/DM/butterfly/Beetles/Coccinellidae/Coccinellid.html"},
	{"nafoku",	"http://nafoku.de/kaefer/coccinellidae/index.htm"},
	{"habitas",	"http://www.habitas.org.uk/ladybirds/gallery.html"},
	{"rutkies",	"http://www.rutkies.de/kaefer/"},
	{"uoguelph",	"http://www.uoguelph.ca/debu/lady/lady-beetles.htm"},
	{"meddonatuurlijkmooi",	"http://meddonatuurlijkmooi.nl/index.php?sub=13&pag=31&sub2=1"},
	{"ladybirds au",	"http://www.ento.csiro.au/biology/ladybirds/speciesIndex.php"},
	{"arthropa",	"http://arthropa.free.fr/index.php?page=liste&css=noir"},
	{"gdeam",	"http://www.gdeam.com/photorama.php?lng=fr"},
	{"biodiversity",	"http://ias.biodiversity.be/species/show/102"},
	{"illustration-nature",	"http://www.illustration-nature.com/site_photos/accueil_photo.htm"},
	{"tolweb",	"http://tolweb.org"},
	{"stippen",	"http://www.stippen.nl/index.php"},
	{"insectimages",	"http://www.insectimages.org/browse/tax.cfm?fam=128"},
	{"alexanderwild",	"http://www.alexanderwild.com"},
	{"butterflyfunfacts",	"http://www.butterflyfunfacts.com/ladybug-lifecycle.php"},
	{"indianaturewatch",	"http://www.indianaturewatch.net/view_cat.php?tag=Ladybird%20Beetle"},
	{"fcps",	"http://www.fcps.edu/islandcreekes/ecology/convergent_ladybug_beetle.htm"},
	{"insectforum",	"http://insectforum.no-ip.org/gods/cgi-bin/leobbs.cgi"},
	{"biolib",	"http://www.biolib.cz/en/taxontree/id10713/"},
	{"hmyz.naturfoto",	"http://hmyz.naturfoto.cz/brouci-sluneckoviti.html"},
	{"macrophotography",	"http://www.macrophotography.cz/index.php"},
	{"photopictura",	"http://www.photopictura.cz/"},
	{"coleopterist",	"http://www.coleopterist.org.uk"},
};

int flickrTotal=32;
char flickr[100][2][260]=
{
	
	{"sanmartin",	"http://www.flickr.com/photos/sanmartin/collections/72157603571001091/"},
	{"arthur_chapman",	"http://www.flickr.com/photos/arthur_chapman/sets/72157609084340321"},
	{"zimbart",	"http://www.flickr.com/photos/zimbart/5770482513/in/set-72157626706069133"},
	{"47108884@N07",	"http://www.flickr.com/photos/47108884@N07/sets/72157623518888471/"},
	{"65645208@N05",	"http://www.flickr.com/photos/65645208@N05/sets/72157627246669977/"},
	{"coleoptera-us",	"http://www.flickr.com/photos/coleoptera-us/sets/72157617782187183"},
	{"adamantine",	"http://www.flickr.com/photos/adamantine/sets/72157624190179278"},
	{"angela-and-andrew",	"http://www.flickr.com/photos/angela-and-andrew/sets/72157601374577063/"},
	{"44055945@N06",	"http://www.flickr.com/photos/44055945@N06/sets/72157626736522336/"},
	{"finklez",	"http://www.flickr.com/photos/finklez/sets/72157613202355692/"},
	{"valter",	"http://www.flickr.com/photos/valter/sets/72157630252982396/"},
	{"joaocoelho",	"http://www.flickr.com/photos/joaocoelho/sets/72157615261006253/"},
	{"fturmog",	"http://www.flickr.com/photos/fturmog/sets/72157625901588307/"},
	{"30063276@N02",	"http://www.flickr.com/photos/30063276@N02/sets/72157608236919795/"},
	{"35142635@N05",	"http://www.flickr.com/photos/35142635@N05/sets/72157622522569801/"},
	{"bettaman",	"http://www.flickr.com/photos/bettaman/"},
	{"suedechen",	"http://www.flickr.com/photos/suedechen/sets/72157627975214454/"},
	{"63662482@N06",	"http://www.flickr.com/photos/63662482@N06/sets/72157631602049647/"},
	{"opoterser",	"http://www.flickr.com/photos/opoterser"},
	{"anitagould",	"http://www.flickr.com/photos/anitagould/sets/72157605944949086/"},
	{"dhobern",	"http://www.flickr.com/photos/dhobern/sets/72157604513109762/"},
	{"31031835@N08",	"http://www.flickr.com/photos/31031835@N08/sets/72157628973463245"},
	{"gbohne",	"http://www.flickr.com/photos/gbohne/sets/72157625385724199/"},
	{"eyeweed",	"http://www.flickr.com/photos/eyeweed/sets/72157603886644004/"},
	{"nhm_beetle_id",	"http://www.flickr.com/photos/nhm_beetle_id/sets/72157627463167314/"},
	{"ortoecologo",	"http://www.flickr.com/photos/ortoecologo/sets/72157623249544241/"},
	{"mmmavocado",	"http://www.flickr.com/photos/mmmavocado/sets/72157623005201377/"},
	{"fanedison",	"http://www.flickr.com/photos/fanedison/sets/72157606538378787/"},
	{"jerryhsu2k",	"http://www.flickr.com/photos/jerryhsu2k/sets/72157594310070249/"},
	{"51708886@N03",	"http://www.flickr.com/photos/51708886@N03/sets/72157627047616023/"},
	{"25258702@N04",	"http://www.flickr.com/photos/25258702@N04/sets/72157615507952635/"},
	{"66062911@N03",	"http://www.flickr.com/photos/66062911@N03/sets/72157629829860293/"},
	
};