//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zogiiadd.rc
//
#define IDD_ZOGIIADD_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_TREE                        1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_SubFamilyEN            1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_SubFamilyCN            1002
#define IDC_EDIT3                       1003
#define IDC_EDIT_GenusEN                1003
#define IDC_EDIT4                       1004
#define IDC_EDIT_GenusCN                1004
#define IDC_EDIT5                       1005
#define IDC_EDIT_SubFamilyTW            1005
#define IDC_EDIT6                       1006
#define IDC_EDIT_GenusTW                1006
#define IDC_COMBO1                      1007
#define IDC_COMBO_ImagoSex              1007
#define IDC_COMBO2                      1008
#define IDC_COMBO_ImagoColorA           1008
#define IDC_COMBO_ImagoElytraColorA     1008
#define IDC_COMBO3                      1009
#define IDC_COMBO_ImagoVillus           1009
#define IDC_COMBO4                      1010
#define IDC_COMBO_ImagoTexture          1010
#define IDC_COMBO_ImagoElytraTexture    1010
#define IDC_COMBO10                     1011
#define IDC_COMBO_OvumSex               1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON_SaveImago            1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON_DeleteImago          1013
#define IDC_EDIT15                      1014
#define IDC_EDIT_code                   1014
#define IDC_BUTTON3                     1015
#define IDC_BUTTON_DiscoveryPicPath     1015
#define IDC_BUTTON_DATAOUT              1015
#define IDC_BUTTON4                     1016
#define IDC_BUTTON_SaveData             1016
#define IDC_EDIT16                      1017
#define IDC_EDIT_TextENPath             1017
#define IDC_BUTTON5                     1018
#define IDC_BUTTON_TextENPath           1018
#define IDC_BUTTON13                    1019
#define IDC_BUTTON_ImagoPicPath         1019
#define IDC_EDIT18                      1020
#define IDC_EDIT_TextCNPath             1020
#define IDC_EDIT7                       1021
#define IDC_EDIT_NameEN                 1021
#define IDC_EDIT8                       1022
#define IDC_EDIT_NameCN                 1022
#define IDC_EDIT9                       1023
#define IDC_EDIT_SpNameEN               1023
#define IDC_EDIT10                      1024
#define IDC_EDIT_SpNameCN               1024
#define IDC_EDIT11                      1025
#define IDC_EDIT_NameTW                 1025
#define IDC_EDIT12                      1026
#define IDC_EDIT_SpNameTW               1026
#define IDC_EDIT13                      1027
#define IDC_EDIT_DiscoveryName          1027
#define IDC_EDIT14                      1028
#define IDC_EDIT_DiscoveryPicPath       1028
#define IDC_BUTTON6                     1029
#define IDC_BUTTON_TextCNPath           1029
#define IDC_EDIT19                      1030
#define IDC_EDIT_TextTWPath             1030
#define IDC_EDIT17                      1031
#define IDC_EDIT_DiscoveryPicInfo       1031
#define IDC_BUTTON7                     1032
#define IDC_BUTTON_TextTWPath           1032
#define IDC_COMBO5                      1033
#define IDC_COMBO_ImagoColorB           1033
#define IDC_COMBO_ImagoElytraColorB     1033
#define IDC_COMBO6                      1034
#define IDC_COMBO_ImagoColorC           1034
#define IDC_COMBO_ImagoElytraColorC     1034
#define IDC_COMBO7                      1035
#define IDC_COMBO_ImagoColorD           1035
#define IDC_COMBO_ImagoElytraColorD     1035
#define IDC_COMBO8                      1036
#define IDC_COMBO_ImagoNo               1036
#define IDC_EDIT20                      1037
#define IDC_EDIT_ImagoPicPath           1037
#define IDC_EDIT21                      1038
#define IDC_EDIT_ImagoPicInfo           1038
#define IDC_DATETIMEPICKER1             1039
#define IDC_DATETIMEPICKER_Date         1039
#define IDC_EDIT22                      1040
#define IDC_EDIT_DataOutputPath         1040
#define IDC_BUTTON8                     1041
#define IDC_BUTTON_DiscoveryPicView     1041
#define IDC_BUTTON_DATAIN               1041
#define IDC_BUTTON9                     1042
#define IDC_BUTTON_TextENView           1042
#define IDC_BUTTON10                    1043
#define IDC_BUTTON_TextCNView           1043
#define IDC_BUTTON11                    1044
#define IDC_BUTTON_TextTWView           1044
#define IDC_BUTTON12                    1045
#define IDC_BUTTON_DeleteData           1045
#define IDC_BUTTON15                    1046
#define IDC_BUTTON_ImagoPicView         1046
#define IDC_BUTTON14                    1047
#define IDC_BUTTON_DataOutputPath       1047
#define IDC_COMBO11                     1048
#define IDC_COMBO_OvumColor             1048
#define IDC_COMBO9                      1049
#define IDC_COMBO_ImagoColorNum         1049
#define IDC_COMBO_ImagoElytraColorNum   1049
#define IDC_COMBO23                     1050
#define IDC_COMBO_PupaSex               1050
#define IDC_COMBO24                     1051
#define IDC_COMBO_PupaColorA            1051
#define IDC_COMBO26                     1052
#define IDC_COMBO_PupaColorB            1052
#define IDC_COMBO15                     1053
#define IDC_COMBO_OvumNo                1053
#define IDC_COMBO25                     1054
#define IDC_COMBO_PupaNo                1054
#define IDC_EDIT23                      1055
#define IDC_EDIT_OvumPicPath            1055
#define IDC_EDIT24                      1056
#define IDC_EDIT_OvumPicInfo            1056
#define IDC_BUTTON16                    1057
#define IDC_BUTTON_SaveOvum             1057
#define IDC_BUTTON17                    1058
#define IDC_BUTTON_DeleteOvum           1058
#define IDC_BUTTON18                    1059
#define IDC_BUTTON_OvumPicPath          1059
#define IDC_BUTTON19                    1060
#define IDC_BUTTON_OvumPicView          1060
#define IDC_COMBO12                     1061
#define IDC_COMBO_LarvaSex              1061
#define IDC_EDIT34                      1062
#define IDC_EDIT_PupaPicPath            1062
#define IDC_COMBO14                     1063
#define IDC_COMBO_LarvaCalthrop         1063
#define IDC_COMBO16                     1064
#define IDC_COMBO_LarvaColorB           1064
#define IDC_COMBO17                     1065
#define IDC_COMBO_LarvaColorC           1065
#define IDC_COMBO18                     1066
#define IDC_COMBO_LarvaColorD           1066
#define IDC_COMBO19                     1067
#define IDC_COMBO_LarvaNo               1067
#define IDC_EDIT25                      1068
#define IDC_EDIT_LarvaPicPath           1068
#define IDC_EDIT26                      1069
#define IDC_EDIT_LarvaPicInfo           1069
#define IDC_BUTTON20                    1070
#define IDC_BUTTON_SaveLarva            1070
#define IDC_BUTTON21                    1071
#define IDC_BUTTON_DeleteLarva          1071
#define IDC_COMBO20                     1072
#define IDC_COMBO_LarvaColorNum         1072
#define IDC_BUTTON22                    1073
#define IDC_BUTTON_LarvaPicPath         1073
#define IDC_BUTTON23                    1074
#define IDC_BUTTON_LarvaPicView         1074
#define IDC_COMBO13                     1075
#define IDC_COMBO_LarvaColorA           1075
#define IDC_COMBO21                     1076
#define IDC_COMBO_LarvaInstar           1076
#define IDC_EDIT35                      1077
#define IDC_EDIT_PupaPicInfo            1077
#define IDC_BUTTON25                    1078
#define IDC_BUTTON_SavePupa             1078
#define IDC_COMBO22                     1079
#define IDC_COMBO_Food                  1079
#define IDC_EDIT27                      1080
#define IDC_BUTTON26                    1080
#define IDC_BUTTON_DeletePupa           1080
#define IDC_EDIT28                      1081
#define IDC_EDIT_FoodNameA              1081
#define IDC_EDIT29                      1082
#define IDC_EDIT_FoodNameB              1082
#define IDC_EDIT30                      1083
#define IDC_EDIT_FoodNameC              1083
#define IDC_BUTTON27                    1084
#define IDC_BUTTON_PupaPicPath          1084
#define IDC_EDIT31                      1085
#define IDC_EDIT_FoodNameD              1085
#define IDC_EDIT32                      1086
#define IDC_EDIT_FoodNameE              1086
#define IDC_EDIT_LivingNameA            1086
#define IDC_EDIT33                      1087
#define IDC_EDIT_FoodNameF              1087
#define IDC_EDIT_LivingNameB            1087
#define IDC_BUTTON28                    1088
#define IDC_BUTTON_PupaPicView          1088
#define IDC_BUTTON24                    1089
#define IDC_BUTTON_SaveFood             1089
#define IDC_EDIT_FoodNameG              1089
#define IDC_EDIT_LivingNameC            1089
#define IDC_COMBO27                     1090
#define IDC_COMBO_PupaColorC            1090
#define IDC_COMBO28                     1091
#define IDC_COMBO_PupaColorD            1091
#define IDC_COMBO29                     1092
#define IDC_COMBO_PupaColorNum          1092
#define IDC_EDIT36                      1093
#define IDC_EDIT_OtherNameA             1093
#define IDC_EDIT37                      1094
#define IDC_EDIT_OtherNameB             1094
#define IDC_EDIT38                      1095
#define IDC_EDIT_OtherNameC             1095
#define IDC_EDIT39                      1096
#define IDC_EDIT_OtherNameD             1096
#define IDC_EDIT40                      1097
#define IDC_EDIT_OtherNameE             1097
#define IDC_EDIT41                      1098
#define IDC_EDIT_OtherNameF             1098
#define IDC_BUTTON29                    1099
#define IDC_BUTTON_SaveOtherName        1099
#define IDC_EDIT_OtherNameG             1099
#define IDC_BUTTON_DataOutput           1100
#define IDC_BUTTON_OpenPath             1101
#define IDC_COMBO_ImagoColorA2          1102
#define IDC_COMBO_ImagoPronotumColorA   1102
#define IDC_COMBO30                     1103
#define IDC_COMBO_PointNum              1103
#define IDC_COMBO_ImagoElytraPointNum   1103
#define IDC_BUTTON_SaveDB               1104
#define IDC_COMBO_ImagoColorB2          1105
#define IDC_COMBO_ImagoPronotumColorB   1105
#define IDC_EDIT_path                   1106
#define IDC_COMBO31                     1107
#define IDC_COMBO_ImagoPronotumTexture  1107
#define IDC_COMBO_ImagoColorC2          1108
#define IDC_COMBO_ImagoPronotumColorC   1108
#define IDC_COMBO_ImagoColorD2          1109
#define IDC_COMBO_ImagoPronotumColorD   1109
#define IDC_COMBO_ImagoColorNum2        1110
#define IDC_COMBO_ImagoPronotumColorNum 1110
#define IDC_COMBO_PointNum2             1111
#define IDC_COMBO_ImagoPronotumPointNum 1111
#define IDC_COMBO_ImagobellyColor       1112
#define IDC_COMBO_LIGHT                 1113
#define IDC_COMBO_LIVING                1114
#define IDC_COMBO_SIZE                  1115
#define IDC_COMBO_PupaType              1116
#define IDC_COMBO_OVERWINTER            1117
#define IDC_COMBO_StartMonth            1118
#define IDC_COMBO_EndMonth              1119
#define IDC_EDIT_CloseupPicPath         1120
#define IDC_EDIT_CloseupPicInfo         1121
#define IDC_BUTTON_SaveCloseup          1122
#define IDC_BUTTON_DeleteCloseup        1123
#define IDC_BUTTON_CloseupPicPath       1124
#define IDC_BUTTON_CloseupPicView       1125
#define IDC_COMBO_CloseupType           1127
#define IDC_COMBO_DiscoverMapA          1128
#define IDC_COMBO_CloseupNo             1141
#define IDC_COMBO_DiscoverMapG          1145
#define IDC_COMBO_DiscoverMapB          1146
#define IDC_COMBO_DiscoverMapH          1147
#define IDC_COMBO_DiscoverMapC          1148
#define IDC_COMBO_DiscoverMapI          1149
#define IDC_COMBO_DiscoverMapD          1150
#define IDC_COMBO_DiscoverMapJ          1151
#define IDC_COMBO_DiscoverMapE          1152
#define IDC_COMBO_DiscoverMapK          1153
#define IDC_COMBO_DiscoverMapF          1154
#define IDC_COMBO_DiscoverMapL          1155

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
