//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zogci.rc
//
#define IDD_ZOGCI_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_ABOUT                       129
#define IDD_SEARCH                      130
#define IDD_RESULT                      131
#define IDD_INFO                        132
#define IDD_Announce                    133
#define IDD_LINK                        135
#define IDD_RESULT_PANNEL               137
#define IDD_PICTURE                     139
#define IDD_MARK                        140
#define IDD_INFO_TXT                    141
#define IDD_MAP                         142
#define IDD_PICWIN                      143
#define IDB_BITMAP_MAP                  145
#define IDD_INFOTXT_PANNEL              146
#define IDD_INFOTXT_INFO                147
#define IDD_COLOR                       148
#define IDB_PUPA_SOFTTHORN              149
#define IDB_CONTOUR_CIRCLE              150
#define IDB_CONTOUR_ELLIPSE             151
#define IDB_CONTOUT_RACTANGLE           152
#define IDB_LARVA_ALLHAIR               153
#define IDB_LARVA_BRANCH                154
#define IDB_LARVA_FLAT                  155
#define IDB_LARVA_HALFHAIR              156
#define IDB_LARVA_NORMAL                157
#define IDB_LARVA_NULLHAIR              158
#define IDB_LARVA_THORN                 159
#define IDB_PUPA_HAIR                   160
#define IDB_PUPA_HARDTHORN              161
#define IDB_PUPA_NORMAL                 162
#define IDD_SEARCH_ELYTRON              163
#define IDD_SEARCH_PRONOTUM             164
#define IDB_ELYTRON_STRIPED             166
#define IDB_ELYTRON_BANDED              167
#define IDB_ELYTRON_CIRCLE              168
#define IDB_ELYTRON_EYE                 169
#define IDB_ELYTRON_SOLID               170
#define IDB_ELYTRON_SPOTS               171
#define IDB_PRONOTUM_2BIG               172
#define IDB_PRONOTUM_SOLID              173
#define IDB_PRONOTUM_SPOTS              174
#define IDC_TREE                        1000
#define IDC_TAB_MAIN                    1001
#define IDC_Announce                    1002
#define IDC_Language                    1003
#define IDC_LanguageButton              1004
#define IDC_Authors                     1005
#define IDC_EMAIL                       1006
#define IDC_WEBSITE                     1007
#define IDC_SOFTVER                     1008
#define IDC_DATABASEVER                 1009
#define IDC_LIST_WEBSITE                1009
#define IDC_LIST_BBS                    1011
#define IDC_LIST_BOOK                   1012
#define IDC_LIST_FLICKR                 1013
#define IDC_EDIT_A                      1014
#define IDC_ADDR                        1017
#define IDC_BUTTON_First                1018
#define IDC_BUTTON_Previous             1019
#define IDC_BUTTON_Next                 1020
#define IDC_BUTTON_Last                 1021
#define IDC_EDIT1                       1022
#define IDC_BUTTON_Jump                 1023
#define IDC_COMBO                       1024
#define IDC_PICWIN                      1029
#define IDC_TAB_INFO                    1030
#define IDC_STATIC_SF                   1031
#define IDC_STATIC_GE                   1032
#define IDC_STATIC_SP                   1033
#define IDC_STATIC_SSP                  1034
#define IDC_STATIC_DISCOVERY            1035
#define IDC_COMBO_COLOR                 1038
#define IDC_BUTTON_MARK                 1039
#define IDC_BUTTON1                     1040
#define IDC_BUTTON_ELYTRON              1040
#define IDC_BUTTON_PICWIN2              1041
#define IDC_BUTTON_PRONOTUM             1041
#define IDC_BUTTON_PICWIN3              1042
#define IDC_BUTTON_PICWIN4              1043
#define IDC_BUTTON_PICWIN5              1044
#define IDC_BUTTON_PICWIN6              1045
#define IDC_BUTTON_PICWIN7              1046
#define IDC_BUTTON_PICWIN8              1047
#define IDC_BUTTON_PICWIN9              1048
#define IDC_BUTTON_PICWIN10             1049
#define IDC_BUTTON_PICWIN11             1050
#define IDC_BUTTON_PICWIN12             1051
#define IDC_BUTTON_PICWIN13             1052
#define IDC_BUTTON_PICWIN14             1053
#define IDC_BUTTON_PICWIN15             1054
#define IDC_BUTTON_PICWIN1              1070
#define IDC_BUTTON_PICWIN16             1071
#define IDC_STATIC_MAP                  1071
#define IDC_BUTTON_PICWIN17             1072
#define IDC_LIST                        1072
#define IDC_BUTTON_PICWIN18             1073
#define IDC_EDIT_TXT                    1073
#define IDC_BUTTON_PICWIN19             1074
#define IDC_BUTTON_PICWIN20             1075
#define IDC_CHECK1                      1075
#define IDC_BUTTON_PICWIN21             1076
#define IDC_CHECK2                      1076
#define IDC_BUTTON_PICWIN22             1077
#define IDC_CHECK3                      1077
#define IDC_BUTTON_PICWIN23             1078
#define IDC_CHECK4                      1078
#define IDC_BUTTON_PICWIN24             1079
#define IDC_CHECK5                      1079
#define IDC_BUTTON_PICWIN25             1080
#define IDC_CHECK6                      1080
#define IDC_BUTTON_PICWIN26             1081
#define IDC_BUTTON_RESET                1081
#define IDC_CHECK_ELYTRON_SPOTS         1081
#define IDC_BUTTON_PICWIN27             1082
#define IDC_VILLUS_NO                   1082
#define IDC_BUTTON_PICWIN28             1083
#define IDC_CHECK_ADULT_SIZE_02         1083
#define IDC_BUTTON_PICWIN29             1084
#define IDC_CHECK_ADULT_SIZE_ANY        1084
#define IDC_BUTTON_PICWIN30             1085
#define IDC_CHECK_ADULT_SIZE_25         1085
#define IDC_CHECK_ADULT_SIZE_58         1086
#define IDC_CHECK11                     1087
#define IDC_CHECK_STRIPED_23            1087
#define IDC_CHECK12                     1088
#define IDC_CHECK_STRIPED_ANY           1088
#define IDC_CHECK26                     1089
#define IDC_CHECK_STRIPED_46            1089
#define IDC_CHECK27                     1090
#define IDC_CHECK_STRIPED_79            1090
#define IDC_CHECK28                     1091
#define IDC_BUTTON_ADULT                1091
#define IDC_CHECK29                     1092
#define IDC_BUTTON_LARVA                1092
#define IDC_BUTTON_PUPA                 1093
#define IDC_CHECK_LARVA_NORMAL          1095
#define IDC_CHECK_STRIPED_1             1095
#define IDC_CHECK_LARVA_BRANCH          1096
#define IDC_CHECK_LARVA_THORN           1097
#define IDC_CHECK_LARVA_ALLHAIR         1098
#define IDC_CHECK_LARVA_HALFHAIR        1099
#define IDC_CHECK_LARVA_NULLHAIR        1100
#define IDC_CHECK_LARVA_FLAT            1101
#define IDC_CHECK_PUPA_NORMAL           1102
#define IDC_CHECK_PUPA_HAIR             1103
#define IDC_CHECK_PUPA_HARDTHORN        1104
#define IDC_CHECK_PUPA_SOFTTHORN        1105
#define IDC_CHECK_LARVA_ALL             1106
#define IDC_CHECK_PUPA_ALL              1107
#define IDC_CHECK_ALLNAME               1108
#define IDC_CHECK_SF                    1109
#define IDC_CHECK_GE                    1110
#define IDC_CHECK_SP                    1111
#define IDC_CHECK_SSP                   1112
#define IDC_CHECK_DOC                   1113
#define IDC_CHECK_ADULT_SIZE_810        1114
#define IDC_CHECK_ADULT_SIZE_M10        1115
#define IDC_CHECK_CONTOUR_ANY           1116
#define IDC_CHECK_STRIPED_1012          1116
#define IDC_CHECK_CONTOUR_CIRCLE        1117
#define IDC_CHECK_STRIPED_M12           1117
#define IDC_CHECK_CONTOUR_ELLIPSE       1118
#define IDC_CHECK_CONTOUR_RACTANGLE     1119
#define IDC_DIET_ANY                    1121
#define IDC_DIET_MEAT                   1122
#define IDC_DIET_PLANT                  1123
#define IDC_DIET_FUNGUS                 1124
#define IDC_VILLUS_ANY                  1125
#define IDC_VILLUS_HAVE                 1126
#define IDC_CHECK_SPOT_ANY              1127
#define IDC_CHECK_SPOT_14               1128
#define IDC_CHECK_SPOT_58               1129
#define IDC_CHECK_SPOT_912              1130
#define IDC_CHECK_SPOT_1316             1131
#define IDC_CHECK_SPOT_1720             1132
#define IDC_CHECK_SPOT_M20              1135
#define IDC_CHECK_COLOR_NUM_ANY         1136
#define IDC_CHECK_COLOR_NUM_1           1137
#define IDC_CHECK_COLOR_NUM_2           1138
#define IDC_CHECK_COLOR_NUM_3           1139
#define IDC_CHECK_COLOR_NUM_4           1140
#define IDC_CHECK_COLOR_NUM_M4          1141
#define IDC_CHECK_ELYTRON_BANDED        1142
#define IDC_CHECK_ELYTRON_CIRCLE        1143
#define IDC_CHECK_ELYTRON_EYE           1144
#define IDC_CHECK_ELYTRON_SOLID         1145
#define IDC_CHECK_ELYTRON_STRIPED       1146
#define IDC_CHECK_ELYTRON_ANY           1147
#define IDC_CHECK_ELYTRON_OTHER         1148
#define IDC_CHECK_PRONOTUM_SOLID        1149
#define IDC_CHECK_PRONOTUM_2BIG         1150
#define IDC_CHECK_PRONOTUM_SPOTS        1151
#define IDC_CHECK_PRONOTUM_ANY          1152
#define IDC_CHECK_PRONOTUM_OTHER        1153
#define IDC_CHECK_SPOT_12               1154
#define IDC_CHECK_SPOT_34               1155
#define IDC_CHECK_SPOT_56               1156
#define IDC_CHECK_SPOT_78               1157
#define IDC_CHECK_SPOT_910              1158
#define IDC_CHECK_SPOT_M10              1159

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
